### ISSUE TITLE
js-logging is exported by hawtio-next so should not need to be defined as a dependency

### ISSUE THREAD

**Issue by phantomjinx** [hawtio/hawtio-online#146]
The `js-logging` library is [exported](https://github.com/hawtio/hawtio-next/blob/main/packages/hawtio/src/core/logging.ts#L6) by hawtio-next and then [used](https://github.com/hawtio/hawtio-online/blob/2.x/packages/kubernetes-api/src/globals.ts#L1) in hawtio-online. However, on execution parts of `js-logging` seems to not be present since an exception is produced:

```
Uncaught (in promise) TypeError: this.createDefaultHandler is not a function
    LocalStorageHawtioLogger http://localhost:2772/static/js/vendors-node_modules_hawtio_react_dist_index_js.chunk.js:107337
    node_modules hawtio/react/dist/index.js@http://localhost:2772/static/js/vendors-node_modules_hawtio_react_dist_index_js.chunk.js:107421
    factory http://localhost:2772/static/js/bundle.js:9592
    __webpack_require__ http://localhost:2772/static/js/bundle.js:8906
    I http://localhost:2772/static/js/bundle.js:9154
    id http://localhost:2772/static/js/bundle.js:9824
    factory http://localhost:2772/static/js/bundle.js:9592
    __webpack_require__ http://localhost:2772/static/js/bundle.js:8906
    fn http://localhost:2772/static/js/bundle.js:9231
    tsx http://localhost:2772/static/js/src_bootstrap_tsx.chunk.js:12
    factory http://localhost:2772/static/js/bundle.js:9592
    __webpack_require__ http://localhost:2772/static/js/bundle.js:8906
    fn http://localhost:2772/static/js/bundle.js:9231
vendors-node_modules_hawtio_react_dist_index_js.chunk.js:107337:26
Firefox can’t establish a connection to the server at ws://localhost:2772/ws. 8 bundle.js:5423:18
Source map error: Error: NetworkError when attempting to fetch resource.
Resource URL: http://localhost:2772/static/js/vendors-node_modules_hawtio_react_dist_index_js.chunk.js
Source Map URL: vendors-node_modules_hawtio_react_dist_index_js.chunk.js.map
Source map error: Error: NetworkError when attempting to fetch resource.
Resource URL: http://localhost:2772/static/js/bundle.js
Source Map URL: bundle.js.map
Source map error: Error: NetworkError when attempting to fetch resource.
Resource URL: http://localhost:2772/static/js/src_bootstrap_tsx.chunk.js
Source Map URL: src_bootstrap_tsx.chunk.js.map
Firefox can’t establish a connection to the server at ws://localhost:2772/ws. bundle.js:5423:18
Firefox can’t establish a connection to the server at ws://localhost:2772/ws. bundle.js:5423:18
```

The workaround is to explicitly include `js-logging` as a [dependency](https://github.com/hawtio/hawtio-online/blob/2.x/packages/kubernetes-api/package.json#L33) and once this is included then the error is avoided.

**Comment by tadayosi** [comment]
Is it still an issue?
